# Site settings
title: The pragmatic developer
subtitle: Wasting time so you don't
email: alexandre.rozier.io@gmail.com
description: Build with Jekyll and Forty theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: It's a secret, shhhhh.

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings

github_url: https://github.com/AlexandreRozier
gitlab_url: https://gitlab.com
googleplus_url: https://plus.google.com
instagram_url: https://instagram.com
linkedin_url: https://fr.linkedin.com/in/alexandrerozier
twitter_url: https://twitter.com/YUNoCode

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/css
    style: compressed