# Site settings
title: The pragmatic developer
subtitle: Developing cool things. Sometimes succeeding.
email: alexandre.rozier.io@gmail.com
description: Built with love, coffee and pain.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Between my desk and my chair
city: Grenoble
state: 
zip_code: 
country: France
phone: It's a secret, shhhhh.
future: true

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings

github_url: https://github.com/AlexandreRozier
gitlab_url: https://gitlab.com
googleplus_url: https://plus.google.com
instagram_url: https://instagram.com
linkedin_url: https://fr.linkedin.com/in/alexandrerozier
twitter_url: https://twitter.com/YUNoCode

# Build settings
markdown: kramdown

sass:
    sass_dir: assets/css
    style: compressed